### ISSUE TITLE
 TypeError: unhashable type

### ISSUE THREAD

**Issue by visayang2005** [nicodv/kmodes#40]
when i commit the code below:

clustermodel=kprototypes.KPrototypes(n_clusters=6, init='Cao', verbose=2)
clustermodel.fit(sd1,categorical=[0,1])

it can't run with the " TypeError: unhashable type", but kmode is ok.  could you pls tell me how can solve this problem? Thank very much!

**Comment by nicodv** [comment]
Please post a full traceback, so that I can locate the error.

**Comment by visayang2005** [comment]
ok, my full code like this, 

from kmodes import kmodes
from kmodes import kprototypes
import pandas as pd
from sklearn import cluster

# the first two varibles of dataframe sd1 is categorical, other varibles is continus
sd1=sd[['state','newmode_id','at_price_scaled','day_diff_scaled', 'time_avg_rate_scaled', 'total_dealnum_scaled', 'total_dealprice_scaled', 'total_dealnum_fws_scaled']]

clustermodel=kprototypes.KPrototypes(n_clusters=6, init='Cao', verbose=2)
cluser=clustermodel.fit_predict(sd1,categorical=[0,1])

**Comment by nicodv** [comment]
Can you post the full error too, please?

**Comment by visayang2005** [comment]
the error is like this:

clustermodel=kprototypes.KPrototypes(n_clusters=6, init='Cao', verbose=2)
clustermodel.fit(sd1,categorical=[0,1])
Traceback (most recent call last):

  File "<ipython-input-10-c73803d1c223>", line 2, in <module>
    clustermodel.fit(sd1,categorical=[0,1])

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 415, in fit
    self.verbose)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 154, in k_prototypes
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 47, in _split_num_cat
    if ii not in categorical]]).astype(np.float64)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1384, in _get_item_cache
    res = cache.get(item)

TypeError: unhashable type


a = [1， 2， 3， 4， 5， 1， 2， 3， 4， 5， 6， 7， 8， 9， 0]
print "orginal:"， a
  File "<ipython-input-11-cbb4f27ebe23>", line 1
    a = [1， 2， 3， 4， 5， 1， 2， 3， 4， 5， 6， 7， 8， 9， 0]
          ^
SyntaxError: invalid syntax


a = [1， 2， 3， 4， 5， 1， 2， 3， 4， 5， 6， 7， 8， 9， 0]
  File "<ipython-input-12-48d4966e004f>", line 1
    a = [1， 2， 3， 4， 5， 1， 2， 3， 4， 5， 6， 7， 8， 9， 0]
          ^
SyntaxError: invalid syntax


a = [1, 2, 3, 4, 5]

print list(set(a))

a = [str（i） for i in a]
  File "<ipython-input-15-163397c55242>", line 1
    a = [str（i） for i in a]
            ^
SyntaxError: invalid syntax


a = [str(i) for i in a]

print "orginal:", a

print list(set(a))

clustermodel.fit(sd1,categorical=[0,1])
Traceback (most recent call last):

  File "<ipython-input-19-04efeb707df8>", line 1, in <module>
    clustermodel.fit(sd1,categorical=[0,1])

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 415, in fit
    self.verbose)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 154, in k_prototypes
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 47, in _split_num_cat
    if ii not in categorical]]).astype(np.float64)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1384, in _get_item_cache
    res = cache.get(item)

TypeError: unhashable type


cluser=clustermodel.fit_predict(sd1,categorical=[0,1])
Traceback (most recent call last):

  File "<ipython-input-20-8e29f41713fd>", line 1, in <module>
    cluser=clustermodel.fit_predict(sd1,categorical=[0,1])

  File "build\bdist.win-amd64\egg\kmodes\kmodes.py", line 374, in fit_predict
    return self.fit(X, **kwargs).labels_

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 415, in fit
    self.verbose)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 154, in k_prototypes
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 47, in _split_num_cat
    if ii not in categorical]]).astype(np.float64)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1384, in _get_item_cache
    res = cache.get(item)

TypeError: unhashable type


cluser=clustermodel.fit_predict(sd1,categorical=[0,1])
Traceback (most recent call last):

  File "<ipython-input-21-8e29f41713fd>", line 1, in <module>
    cluser=clustermodel.fit_predict(sd1,categorical=[0,1])

  File "build\bdist.win-amd64\egg\kmodes\kmodes.py", line 374, in fit_predict
    return self.fit(X, **kwargs).labels_

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 415, in fit
    self.verbose)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 154, in k_prototypes
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 47, in _split_num_cat
    if ii not in categorical]]).astype(np.float64)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1384, in _get_item_cache
    res = cache.get(item)

TypeError: unhashable type


Thanks very much

**Comment by visayang2005** [comment]
sorry, pls ignore before,  use this:

cluser=clustermodel.fit_predict(sd1,categorical=[0,1])
Traceback (most recent call last):

  File "<ipython-input-21-8e29f41713fd>", line 1, in <module>
    cluser=clustermodel.fit_predict(sd1,categorical=[0,1])

  File "build\bdist.win-amd64\egg\kmodes\kmodes.py", line 374, in fit_predict
    return self.fit(X, **kwargs).labels_

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 415, in fit
    self.verbose)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 154, in k_prototypes
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 47, in _split_num_cat
    if ii not in categorical]]).astype(np.float64)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)

  File "D:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1384, in _get_item_cache
    res = cache.get(item)

TypeError: unhashable type

**Comment by visayang2005** [comment]
Hi  Nico,

The full error like this, can you help me to solve it, I really appreciate your help.

cluser=clustermodel.fit_predict(sd1,categorical=[0,1])
Traceback (most recent call last):

File "", line 1, in 
cluser=clustermodel.fit_predict(sd1,categorical=[0,1])

File "build\bdist.win-amd64\egg\kmodes\kmodes.py", line 374, in fit_predict
return self.fit(X, **kwargs).labels_

File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 415, in fit
self.verbose)

File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 154, in k_prototypes
Xnum, Xcat = _split_num_cat(X, categorical)

File "build\bdist.win-amd64\egg\kmodes\kprototypes.py", line 47, in _split_num_cat
if ii not in categorical]]).astype(np.float64)

File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2059, in getitem
return self._getitem_column(key)

File "D:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
return self._get_item_cache(key)

File "D:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1384, in _get_item_cache
res = cache.get(item)

TypeError: unhashable type

**Comment by nicodv** [comment]
Try presenting a numpy array to the algorithm, instead of a pandas DataFrame: `cluster=clustermodel.fit_predict(sd1.values,categorical=[0,1])`

**Comment by nicodv** [comment]
Since it seems reasonable to have users present pandas DataFrames as inputs to the algorithm, it's probably a good idea to include a check (e.g., `'pandas' in str(X.__class__)`) and do a `X.values` if True.

Alternatively, make sure all operations (such as the one that caused this bug) support DataFrames, but that's hard to implement and check consistently.

**Comment by visayang2005** [comment]
Thanks, Nico. My problem is solved by using a numpy array to the algorithm.

**Comment by nicodv** [comment]
This should no longer occur: https://github.com/nicodv/kmodes/commit/a30da8060f8ca784105528766bc063974ceb5bf0

**Comment by cibic89** [comment]
This is not fixed in the latest version. Added the .values to the dataframe and worked like a charm.
