### ISSUE TITLE
Using Structured ndarray

### ISSUE THREAD

**Issue by endo9e7a6** [nicodv/kmodes#78]
Hi, im trying to run Kprototypes with an structured ndarray, ie:

>>>X
array([(b'30SEP09', 30, b'N',  1522.37, 242.,   6., b'N', 10, 0, 999, 0.21264229, 0.16053661),
       (b'30JUN09', 49, b'N', 16390.44, 182.,   6., b'S', 12, 0, 999, 0.21264229, 0.16053661),
       (b'30JUN09', 49, b'N', 21610.55, 193.,   6., b'S', 12, 0, 999, 0.21264229, 0.16053661),
       ...,
       (b'31MAR10', 49, b'N', 13167.72, 535., 618., b'N', 12, 0, 660, 0.07903281, 0.05966668),
       (b'31MAR10', 49, b'N',  4189.49, 179., 623., b'N', 12, 0, 660, 0.07903281, 0.05966668),
       (b'31MAR10', 49, b'N', 21140.61, 575., 637., b'N', 12, 0, 660, 0.07903281, 0.05966668)],
      dtype=[('fec_mes', 'O'), ('S1EMP', '<i4'), ('EXP_MES', 'O'), ('importh', '<f8'), ('PCO_IDPUNSCO', '<f8'), ('PCL_IDPUNSCO_T8', '<f8'), ('EXP_POST_total', 'O'), ('num_meses_vivo_total', '<i4'), ('Lim_Inf', '<i4'), ('Lim_Sup', '<i4'), ('PD_Eco', '<f8'), ('PD_TTC', '<f8')])

And I'm getting an error while executting the algorithm:
>>>kproto = KPrototypes(n_clusters=8, init='Cao', verbose=0)
>>>clusters = kproto.fit_predict(X, categorical=[0, 1, 2, 6])
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\***\AppData\Roaming\JetBrains\PyCharm 2018.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/***/PycharmProjects/BigData/Clustering/KProrotypes/main.py", line 32, in <module>
    clusters = kproto.fit_predict(X, categorical=[0, 1])
  File "C:\Users\***\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes-0.9-py3.6.egg\kmodes\kmodes.py", line 375, in fit_predict
    return self.fit(X, **kwargs).predict(X, **kwargs)
  File "C:\Users\***\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes-0.9-py3.6.egg\kmodes\kprototypes.py", line 419, in fit
    self.verbose)
  File "C:\Users\x267781\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes-0.9-py3.6.egg\kmodes\kprototypes.py", line 146, in k_prototypes
    assert len(categorical) != X.shape[1], \
IndexError: tuple index out of range

Can you give some fix to this issue?
Thanks in advance!

**Comment by endo9e7a6** [comment]
My matrix X shape is:
\>\>\>X.shape
>>>(100001,)
