### ISSUE TITLE
Error when using the euclidean_dissim function

### ISSUE THREAD

**Issue by vlall** [nicodv/kmodes#82]
I tried running one of the other built-in dissim functions, `euclidean_dissim`:
```
km = kmodes.KModes(n_clusters=5, init="Huang", n_init=1, verbose=1, cat_dissim=euclidean_dissim)
```

And received this error:
```
Traceback (most recent call last):
  File "kmode_main.py", line 41, in <module>
    clusters = km.fit_predict(x)
  File "/usr/local/lib/python3.6/site-packages/kmodes/kmodes.py", line 376, in fit_predict
    return self.fit(X, **kwargs).predict(X, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kmodes/kmodes.py", line 367, in fit
    self.verbose)
  File "/usr/local/lib/python3.6/site-packages/kmodes/kmodes.py", line 203, in k_modes
    centroids = init_huang(X, n_clusters, dissim)
  File "/usr/local/lib/python3.6/site-packages/kmodes/kmodes.py", line 41, in init_huang
    ndx = np.argsort(dissim(X, centroids[ik]))
  File "/usr/local/lib/python3.6/site-packages/kmodes/util/dissim.py", line 15, in euclidean_dissim
    if np.isnan(a).any() or np.isnan(b).any():
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
````

**Comment by nicodv** [comment]
@vlall The Euclidian dissimilarity is used by `kprototypes` for the numerical columns. It doesn't make sense to use it with categorical features.
